In [2]:
import sqlite3
import pandas as pd
import numpy as np

In [3]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".sqlite"):
            print(os.path.join(root, file))

.\travel.sqlite

In [4]:
import sqlite3

conn = sqlite3.connect(
    r"C:\Users\adeeb\Downloads\archive (5)\travel.sqlite"
)

In [5]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\adeeb\anaconda_projects\37979713-7dc1-45e6-9347-d65494121327
['.ipynb_checkpoints', '01_database_exploration.ipynb', '01_database_exploration1.ipynb', 'travel.sqlite']

In [6]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

tables = pd.read_sql(query, conn)
tables

              name
0   aircrafts_data
1    airports_data
2  boarding_passes
3         bookings
4          flights
5            seats
6   ticket_flights
7          tickets

In [7]:
import os

print(os.path.getsize("travel.sqlite"))

0

In [8]:
cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table';
""")

print(cursor.fetchall())

[('aircrafts_data',), ('airports_data',), ('boarding_passes',), ('bookings',), ('flights',), ('seats',), ('ticket_flights',), ('tickets',)]

In [9]:
import os

for root, dirs, files in os.walk("C:\\Users\\adeeb"):
    for file in files:
        if file == "travel.sqlite":
            full_path = os.path.join(root, file)
            size_mb = os.path.getsize(full_path) / (1024 * 1024)
            print(f"{size_mb:.2f} MB  -->  {full_path}")

0.00 MB  -->  C:\Users\adeeb\anaconda_projects\37979713-7dc1-45e6-9347-d65494121327\travel.sqlite
104.46 MB  -->  C:\Users\adeeb\Downloads\archive (5)\travel.sqlite
104.46 MB  -->  C:\Users\adeeb\OneDrive\Documents\SkyInsight-Airline-Analytics\Data\Raw\travel.sqlite

In [14]:
def explore_table(table_name):
    df = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5", conn)

    print("=" * 70)
    print(f"TABLE: {table_name}")
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nSample Data:")
    display(df)

Explore every table

In [15]:
for table in tables["name"]:
    explore_table(table)

======================================================================
TABLE: aircrafts_data
======================================================================

Shape:
(5, 3)

Columns:
['aircraft_code', 'model', 'range']

Data Types:
aircraft_code    object
model            object
range             int64
dtype: object

Sample Data:

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600

======================================================================
TABLE: airports_data
======================================================================

Shape:
(5, 5)

Columns:
['airport_code', 'airport_name', 'city', 'coordinates', 'timezone']

Data Types:
airport_code    object
airport_name    object
city            object
coordinates     object
timezone        object
dtype: object

Sample Data:

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin

======================================================================
TABLE: boarding_passes
======================================================================

Shape:
(5, 4)

Columns:
['ticket_no', 'flight_id', 'boarding_no', 'seat_no']

Data Types:
ticket_no      object
flight_id       int64
boarding_no     int64
seat_no        object
dtype: object

Sample Data:

       ticket_no  flight_id  boarding_no seat_no
0  0005435212351      30625            1      2D
1  0005435212386      30625            2      3G
2  0005435212381      30625            3      4H
3  0005432211370      30625            4      5D
4  0005435212357      30625            5     11A

======================================================================
TABLE: bookings
======================================================================

Shape:
(5, 3)

Columns:
['book_ref', 'book_date', 'total_amount']

Data Types:
book_ref        object
book_date       object
total_amount     int64
dtype: object

Sample Data:

  book_ref               book_date  total_amount
0   00000F  2017-07-05 03:12:00+03        265700
1   000012  2017-07-14 09:02:00+03         37900
2   000068  2017-08-15 14:27:00+03         18100
3   000181  2017-08-10 13:28:00+03        131800
4   0002D8  2017-08-07 21:40:00+03         23600

======================================================================
TABLE: flights
======================================================================

Shape:
(5, 10)

Columns:
['flight_id', 'flight_no', 'scheduled_departure', 'scheduled_arrival', 'departure_airport', 'arrival_airport', 'status', 'aircraft_code', 'actual_departure', 'actual_arrival']

Data Types:
flight_id               int64
flight_no              object
scheduled_departure    object
scheduled_arrival      object
departure_airport      object
arrival_airport        object
status                 object
aircraft_code          object
actual_departure       object
actual_arrival         object
dtype: object

Sample Data:

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N

======================================================================
TABLE: seats
======================================================================

Shape:
(5, 3)

Columns:
['aircraft_code', 'seat_no', 'fare_conditions']

Data Types:
aircraft_code      object
seat_no            object
fare_conditions    object
dtype: object

Sample Data:

  aircraft_code seat_no fare_conditions
0           319      2A        Business
1           319      2C        Business
2           319      2D        Business
3           319      2F        Business
4           319      3A        Business

======================================================================
TABLE: ticket_flights
======================================================================

Shape:
(5, 4)

Columns:
['ticket_no', 'flight_id', 'fare_conditions', 'amount']

Data Types:
ticket_no          object
flight_id           int64
fare_conditions    object
amount              int64
dtype: object

Sample Data:

       ticket_no  flight_id fare_conditions  amount
0  0005432159776      30625        Business   42100
1  0005435212351      30625        Business   42100
2  0005435212386      30625        Business   42100
3  0005435212381      30625        Business   42100
4  0005432211370      30625        Business   42100

======================================================================
TABLE: tickets
======================================================================

Shape:
(5, 3)

Columns:
['ticket_no', 'book_ref', 'passenger_id']

Data Types:
ticket_no       object
book_ref        object
passenger_id    object
dtype: object

Sample Data:

       ticket_no book_ref passenger_id
0  0005432000987   06B046  8149 604011
1  0005432000988   06B046  8499 420203
2  0005432000989   E170C3  1011 752484
3  0005432000990   E170C3  4849 400049
4  0005432000991   F313DD  6615 976589

Count rows AND columns automatically

In [20]:
summary = []

for table in tables["name"]:
    
    rows = pd.read_sql(
        f"SELECT COUNT(*) AS row_count FROM {table}",
        conn
    ).iloc[0,0]
    
    cols = pd.read_sql(
        f"SELECT * FROM {table} LIMIT 1",
        conn
    ).shape[1]
    
    summary.append([table, rows, cols])

summary = pd.DataFrame(
    summary,
    columns=["Table","Rows","Columns"]
)
summary

             Table     Rows  Columns
0   aircrafts_data        9        3
1    airports_data      104        5
2  boarding_passes   579686        4
3         bookings   262788        3
4          flights    33121       10
5            seats     1339        3
6   ticket_flights  1045726        4
7          tickets   366733        3

summary

In [22]:
bookings = pd.read_sql(
    "SELECT * FROM bookings",
    conn
)

type(bookings)

bookings.head()

bookings.info()

bookings.isnull().sum()

bookings.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262788 entries, 0 to 262787
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   book_ref      262788 non-null  object
 1   book_date     262788 non-null  object
 2   total_amount  262788 non-null  int64
dtypes: int64(1), object(2)
memory usage: 6.0+ MB

np.int64(0)

In [11]:
tickets.info()
ticket_flights.info()
bookings.info()
airports.info()
aircrafts.info()
boarding_passes.info()
seats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366733 entries, 0 to 366732
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ticket_no     366733 non-null  object
 1   book_ref      366733 non-null  object
 2   passenger_id  366733 non-null  object
dtypes: object(3)
memory usage: 8.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045726 entries, 0 to 1045725
Data columns (total 4 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   ticket_no        1045726 non-null  object
 1   flight_id        1045726 non-null  int64
 2   fare_conditions  1045726 non-null  object
 3   amount           1045726 non-null  int64
dtypes: int64(2), object(2)
memory usage: 31.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262788 entries, 0 to 262787
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   book_ref      262788 non-null  object
 1   book_date     262788 non-null  object
 2   total_amount  262788 non-null  int64
dtypes: int64(1), object(2)
memory usage: 6.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   airport_code  104 non-null    object
 1   airport_name  104 non-null    object
 2   city          104 non-null    object
 3   coordinates   104 non-null    object
 4   timezone      104 non-null    object
dtypes: object(5)
memory usage: 4.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   aircraft_code  9 non-null      object
 1   model          9 non-null      object
 2   range          9 non-null      int64
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579686 entries, 0 to 579685
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ticket_no    579686 non-null  object
 1   flight_id    579686 non-null  int64
 2   boarding_no  579686 non-null  int64
 3   seat_no      579686 non-null  object
dtypes: int64(2), object(2)
memory usage: 17.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   aircraft_code    1339 non-null   object
 1   seat_no          1339 non-null   object
 2   fare_conditions  1339 non-null   object
dtypes: object(3)
memory usage: 31.5+ KB

Data Profiling

In [25]:
bookings = pd.read_sql("SELECT * FROM bookings", conn)

profile = {
    "Rows": bookings.shape[0],
    "Columns": bookings.shape[1],
    "Missing Values": bookings.isnull().sum().sum(),
    "Duplicate Rows": bookings.duplicated().sum(),
    "Memory (MB)": round(bookings.memory_usage(deep=True).sum() / 1024**2, 2)
}

profile

{'Rows': 262788,
 'Columns': 3,
 'Missing Values': np.int64(0),
 'Duplicate Rows': np.int64(0),
 'Memory (MB)': np.float64(33.58)}

reusable Database Profiler

In [31]:
profiles = []

for table in tables["name"]:

    df = pd.read_sql(
        f"SELECT * FROM {table}",
        conn
    )

    profile = {
        "Table": table,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum(),
        "Memory (MB)": round(
            df.memory_usage(deep=True).sum() / 1024**2,
            2
        )
    }

    profiles.append(profile)

profile_df = pd.DataFrame(profiles)

profile_df = profile_df.sort_values(
    by="Rows",
    ascending=False
)

profile_df = profile_df.reset_index(drop=True)

profile_df

,Table,Rows,Columns,Missing Values,Duplicate Rows,Memory (MB)
0,ticket_flights,1045726,4,0,0,133.74
1,boarding_passes,579686,4,0,0,71.68
2,tickets,366733,3,0,0,61.90
3,bookings,262788,3,0,0,33.58
4,flights,33121,10,0,0,17.06
5,seats,1339,3,0,0,0.20
6,airports_data,104,5,0,0,0.06
7,aircrafts_data,9,3,0,0,0.00

what's inside each table?

Step 1: Create a profiling function

In [32]:
def profile_table(table_name):
    
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn)

    print("=" * 70)
    print(f"TABLE: {table_name}")
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nFirst Five Rows:")
    display(df.head())

In [33]:
profile_table("bookings")

======================================================================
TABLE: bookings
======================================================================

Shape:
(262788, 3)

Data Types:
book_ref        object
book_date       object
total_amount     int64
dtype: object

Missing Values:
book_ref        0
book_date       0
total_amount    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

  book_ref               book_date  total_amount
0   00000F  2017-07-05 03:12:00+03        265700
1   000012  2017-07-14 09:02:00+03         37900
2   000068  2017-08-15 14:27:00+03         18100
3   000181  2017-08-10 13:28:00+03        131800
4   0002D8  2017-08-07 21:40:00+03         23600

Step 2 :Automate it

In [34]:
for table in tables["name"]:
    profile_table(table)

======================================================================
TABLE: aircrafts_data
======================================================================

Shape:
(9, 3)

Data Types:
aircraft_code    object
model            object
range             int64
dtype: object

Missing Values:
aircraft_code    0
model            0
range            0
dtype: int64

Duplicate Rows:
0

First Five Rows:

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600

======================================================================
TABLE: airports_data
======================================================================

Shape:
(104, 5)

Data Types:
airport_code    object
airport_name    object
city            object
coordinates     object
timezone        object
dtype: object

Missing Values:
airport_code    0
airport_name    0
city            0
coordinates     0
timezone        0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin

======================================================================
TABLE: boarding_passes
======================================================================

Shape:
(579686, 4)

Data Types:
ticket_no      object
flight_id       int64
boarding_no     int64
seat_no        object
dtype: object

Missing Values:
ticket_no      0
flight_id      0
boarding_no    0
seat_no        0
dtype: int64

Duplicate Rows:
0

First Five Rows:

       ticket_no  flight_id  boarding_no seat_no
0  0005435212351      30625            1      2D
1  0005435212386      30625            2      3G
2  0005435212381      30625            3      4H
3  0005432211370      30625            4      5D
4  0005435212357      30625            5     11A

======================================================================
TABLE: bookings
======================================================================

Shape:
(262788, 3)

Data Types:
book_ref        object
book_date       object
total_amount     int64
dtype: object

Missing Values:
book_ref        0
book_date       0
total_amount    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

  book_ref               book_date  total_amount
0   00000F  2017-07-05 03:12:00+03        265700
1   000012  2017-07-14 09:02:00+03         37900
2   000068  2017-08-15 14:27:00+03         18100
3   000181  2017-08-10 13:28:00+03        131800
4   0002D8  2017-08-07 21:40:00+03         23600

======================================================================
TABLE: flights
======================================================================

Shape:
(33121, 10)

Data Types:
flight_id               int64
flight_no              object
scheduled_departure    object
scheduled_arrival      object
departure_airport      object
arrival_airport        object
status                 object
aircraft_code          object
actual_departure       object
actual_arrival         object
dtype: object

Missing Values:
flight_id              0
flight_no              0
scheduled_departure    0
scheduled_arrival      0
departure_airport      0
arrival_airport        0
status                 0
aircraft_code          0
actual_departure       0
actual_arrival         0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N

======================================================================
TABLE: seats
======================================================================

Shape:
(1339, 3)

Data Types:
aircraft_code      object
seat_no            object
fare_conditions    object
dtype: object

Missing Values:
aircraft_code      0
seat_no            0
fare_conditions    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

  aircraft_code seat_no fare_conditions
0           319      2A        Business
1           319      2C        Business
2           319      2D        Business
3           319      2F        Business
4           319      3A        Business

======================================================================
TABLE: ticket_flights
======================================================================

Shape:
(1045726, 4)

Data Types:
ticket_no          object
flight_id           int64
fare_conditions    object
amount              int64
dtype: object

Missing Values:
ticket_no          0
flight_id          0
fare_conditions    0
amount             0
dtype: int64

Duplicate Rows:
0

First Five Rows:

       ticket_no  flight_id fare_conditions  amount
0  0005432159776      30625        Business   42100
1  0005435212351      30625        Business   42100
2  0005435212386      30625        Business   42100
3  0005435212381      30625        Business   42100
4  0005432211370      30625        Business   42100

======================================================================
TABLE: tickets
======================================================================

Shape:
(366733, 3)

Data Types:
ticket_no       object
book_ref        object
passenger_id    object
dtype: object

Missing Values:
ticket_no       0
book_ref        0
passenger_id    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

       ticket_no book_ref passenger_id
0  0005432000987   06B046  8149 604011
1  0005432000988   06B046  8499 420203
2  0005432000989   E170C3  1011 752484
3  0005432000990   E170C3  4849 400049
4  0005432000991   F313DD  6615 976589

In [37]:
tables_dict = {
    "aircrafts": aircrafts,
    "airports": airports,
    "boarding_passes": boarding_passes,
    "bookings": bookings,
    "flights": flights,
    "seats": seats,
    "ticket_flights": ticket_flights,
    "tickets": tickets
}

for name, df in tables_dict.items():
    print(f"\n{name}")
    print(df.isnull().sum())

aircrafts
aircraft_code    0
model            0
range            0
dtype: int64

airports
airport_code    0
airport_name    0
city            0
coordinates     0
timezone        0
dtype: int64

boarding_passes
ticket_no      0
flight_id      0
boarding_no    0
seat_no        0
dtype: int64

bookings
book_ref        0
book_date       0
total_amount    0
dtype: int64

flights
flight_id              0
flight_no              0
scheduled_departure    0
scheduled_arrival      0
departure_airport      0
arrival_airport        0
status                 0
aircraft_code          0
actual_departure       0
actual_arrival         0
dtype: int64

seats
aircraft_code      0
seat_no            0
fare_conditions    0
dtype: int64

ticket_flights
ticket_no          0
flight_id          0
fare_conditions    0
amount             0
dtype: int64

tickets
ticket_no       0
book_ref        0
passenger_id    0
dtype: int64

In [38]:
flights[
    (flights["departure_airport"] == "AAQ") &
    (flights["status"] != "Cancelled")
]

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
20991,20981,PG0252,2017-07-21 13:05:00+03,2017-07-21 14:45:00+03,AAQ,SVO,Arrived,733,2017-07-21 13:08:00+03,2017-07-21 14:47:00+03
20992,20982,PG0252,2017-07-17 13:05:00+03,2017-07-17 14:45:00+03,AAQ,SVO,Arrived,733,2017-07-17 13:07:00+03,2017-07-17 14:47:00+03
20993,20983,PG0252,2017-09-03 13:05:00+03,2017-09-03 14:45:00+03,AAQ,SVO,Scheduled,733,\N,\N
20994,20984,PG0252,2017-09-02 13:05:00+03,2017-09-02 14:45:00+03,AAQ,SVO,Scheduled,733,\N,\N
20995,20985,PG0252,2017-08-29 13:05:00+03,2017-08-29 14:45:00+03,AAQ,SVO,Scheduled,733,\N,\N
...,...,...,...,...,...,...,...,...,...,...
21117,21107,PG0480,2017-09-10 12:25:00+03,2017-09-10 13:15:00+03,AAQ,EGO,Scheduled,SU9,\N,\N
21118,21108,PG0480,2017-07-24 12:25:00+03,2017-07-24 13:15:00+03,AAQ,EGO,Arrived,SU9,2017-07-24 12:27:00+03,2017-07-24 13:17:00+03
21119,21109,PG0480,2017-07-25 12:25:00+03,2017-07-25 13:15:00+03,AAQ,EGO,Arrived,SU9,2017-07-25 12:26:00+03,2017-07-25 13:16:00+03
21120,21110,PG0480,2017-08-08 12:25:00+03,2017-08-08 13:15:00+03,AAQ,EGO,Arrived,SU9,2017-08-08 12:29:00+03,2017-08-08 13:18:00+03
21121,21111,PG0480,2017-08-22 12:25:00+03,2017-08-22 13:15:00+03,AAQ,EGO,Scheduled,SU9,\N,\N

In [41]:
flights.loc[
    flights["status"] == "Cancelled",
    ["flight_no", "status", "scheduled_departure"]
]

      flight_no     status     scheduled_departure
13       PG0059  Cancelled  2017-09-14 12:25:00+03
677      PG0416  Cancelled  2017-09-14 19:20:00+03
739      PG0054  Cancelled  2017-08-12 17:05:00+03
832      PG0045  Cancelled  2017-09-14 11:45:00+03
884      PG0341  Cancelled  2017-09-14 10:50:00+03
...         ...        ...                     ...
32805    PG0080  Cancelled  2017-09-14 11:25:00+03
32870    PG0616  Cancelled  2017-09-10 09:20:00+03
32960    PG0550  Cancelled  2017-09-14 09:05:00+03
33051    PG0359  Cancelled  2017-09-14 14:30:00+03
33098    PG0063  Cancelled  2017-09-14 19:25:00+03

[414 rows x 3 columns]

total revenue generated by each flight_id and return the top 10 flights.

In [46]:
revenue_by_flight  = ticket_flights.groupby("flight_id")["amount"].sum().sort_values(ascending = False).head(10)
revenue_by_flight

flight_id
2354     17146600
26212    17023600
2364     16962100
2330     16900600
2329     16894400
2341     16839100
2369     16777600
2344     16777600
26162    16593100
2332     16593100
Name: amount, dtype: int64

In [59]:
# Q1: Which routes generate the highest total revenue?
# Route is treated as a bidirectional airport pair.


route_revenue = pd.read_sql_query("""
    SELECT
        CASE
            WHEN f.departure_airport < f.arrival_airport
            THEN f.departure_airport || ' ↔ ' || f.arrival_airport
            ELSE f.arrival_airport || ' ↔ ' || f.departure_airport
        END AS route,

        SUM(tf.amount) AS total_revenue

    FROM ticket_flights AS tf

    JOIN flights AS f
        ON tf.flight_id = f.flight_id

    GROUP BY
        CASE
            WHEN f.departure_airport < f.arrival_airport
            THEN f.departure_airport || ' ↔ ' || f.arrival_airport
            ELSE f.arrival_airport || ' ↔ ' || f.departure_airport
        END

    ORDER BY total_revenue DESC
""", conn)

route_revenue.head(10)


route_revenue.shape


route_revenue.info()


route_revenue.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   route          229 non-null    object
 1   total_revenue  229 non-null    int64
dtypes: int64(1), object(1)
memory usage: 3.7+ KB

       route  total_revenue
0  DME ↔ KHV     1487276100
1  DME ↔ OVB     1079722600
2  KHV ↔ LED     1006423100
3  OVB ↔ SVO      904181600
4  IKT ↔ LED      815653300
5  SVO ↔ SVX      556222600
6  AER ↔ SVO      516307500
7  IKT ↔ KZN      465865200
8  SVO ↔ UUS      458787600
9  KJA ↔ SVO      416379800

In [60]:
Q:What proportion of total revenue comes from each route, and how quickly does cumulative revenue build up?


# Calculate total revenue across all routes
total_revenue = route_revenue["total_revenue"].sum()

# Calculate each route's percentage contribution to total revenue
route_revenue["revenue_share"] = (
    route_revenue["total_revenue"] / total_revenue * 100
)

# Calculate cumulative revenue contribution as we move down the ranked routes
route_revenue["cumulative_revenue_share"] = (
    route_revenue["revenue_share"].cumsum()
)

# Display the top 10 routes
route_revenue.head(10)

       route  total_revenue  revenue_share  cumulative_revenue_share
0  DME ↔ KHV     1487276100       7.161735                  7.161735
1  DME ↔ OVB     1079722600       5.199228                 12.360962
2  KHV ↔ LED     1006423100       4.846266                 17.207228
3  OVB ↔ SVO      904181600       4.353939                 21.561167
4  IKT ↔ LED      815653300       3.927645                 25.488812
5  SVO ↔ SVX      556222600       2.678399                 28.167211
6  AER ↔ SVO      516307500       2.486194                 30.653405
7  IKT ↔ KZN      465865200       2.243298                 32.896703
8  SVO ↔ UUS      458787600       2.209217                 35.105920
9  KJA ↔ SVO      416379800       2.005009                 37.110928